### ISSUE TITLE
Performances

### ISSUE THREAD

**Issue by dddomodossola** [dddomodossola/PFD#15]
@AndKe I pushed an update on branch **cutting_edge_performances". Please give it a try. 
You will need to install pyvips (it is used to convert svg to png):
- installation instructions https://pypi.org/project/pyvips/
- win64 binaries https://github.com/libvips/libvips/releases 

I know that some text labels are placed incorrectly and text font is different than previous, but I need to know if performances are better. 

;-)

**Comment by AndKe** [comment]
Thank you.
On my computer, it was as easy as pip3 install pyvips. (most likely the other libraries were installed before)
on the RPi - I also needed sudo apt install libvips-doc libvips-tools libvips42 

I did performance-testing both on my workstation and RPi4 
From my workstation: streamed to glass + bowser.
From RPI - streamed to glass + two browsers (additional browser windows seems )

In short: yes - the performance on glass is much better.
**All observations below are independent of where the PFD was running (on RPI4, or lots of CPU)**

1: The update interval does vary a bit, it change quickly 3-4 times, then "pause" then change quickly 3-4 times.
the red flashing area, seems to keep a steady rate, so I am not sure what causes it.. steady rate of change would be nice, as the rate of attitude/speed change is important feedback to the pilot.

(if you play video I VLC, select "playback speed-slower" a few times)
https://user-images.githubusercontent.com/1468842/113473466-f05c7480-9469-11eb-8a38-86e05a28a6d5.mp4

2: Mozilla /(Firefox) based browsers, do "blink" between updates - luckily this is not an issue for glass.
https://user-images.githubusercontent.com/1468842/113473490-184bd800-946a-11eb-8db0-540fd1530370.mp4
- this is not of high importance (I think)  - maybe just some Mozilla bug?

3: The rapidly alternating red-black (INOP alarm) reveals that some updates are lost to the google glass, 
however, I see no reason to alternate the color this fast, so the issue will likely not be noticeable in real life.

**Comment by dddomodossola** [comment]
@AndKe  To make the refresh stable you should reduce update frequency. The bug you found on Mozilla can't be prevented, we have luck to not see it on glasses.

**Comment by dddomodossola** [comment]
@AndKe Maybe this is not the best idea to improve performances. We should reduce svg elements to make it easier for the glasses to render the pfd.

**Comment by AndKe** [comment]
I did some data capture to better understand the performance limitations. 

Logged TCP data troughput - all while rendering the test motion - received by desktop browser:
The "standard" version (that does update_interval=0.3 , works well on glass)  147kb/s    steady 51% Glass CPU (no overheating)
The "split" version  (that performed worse) at update_interval=0.3                   206kb/s    steady 58% Glass CPU, but it overheats shortly and performance drops, most likely due to speedstepping/downclocking
The "performance" version, update_interval=0.1                                               364kb/s  mostly 48 and 50% CPU , some peaks to 64% - no sign of overheating.  (some skipp ed updates)

The "performance" version with update_interval=0.2   : 33% CPU  (some, fewer, skipped updates visible due to alternating color)

I would say that the performance update with 5hz refresh rate is the best tradeoff so far, it is a pity the fonts got messed up.
Also 5hz is fine for all practical needs.

**Comment by dddomodossola** [comment]
And so you want to keep the *performace* version,  and we have just to fix font and labels positions. Is this correct?

**Comment by AndKe** [comment]
@dddomodossola  I've seen the comment you wrote regarding "We should reduce svg elements to make it easier"
I am happy with squeezing 5hz out of it.
As for reducing svg elements, I barely know what counts toward them, or whatever each and every polygon and line is an svg element, or mow much can be saved.
What I do know, is that besides a few "bugs" (simple symbols for target altitude, heading, speed)  - things like that - I have no more graphic requests)

I don't fully understand the complexity of fixing up the visual issues of pyvips vs reducing svg's and the possible performance gain by doing so  (and visual changes that involve)   - So I leave that decision entirely to you. 

My own preference would be not to depend on another library (pyvips) that apparently can mess things up again if it someday starts to render fonts/things like a browser does.  On the other hand, it seems like a quick way from 3.3Hz to 5Hz

**Comment by AndKe** [comment]
additional observations/thoughts:  As you know, at a time I did reduce amount of items on pitch/roll indicator in attempt to improve the performance.
before:
![Screenshot from 2021-04-04 09-44-53](https://user-images.githubusercontent.com/1468842/113502165-c7e87f00-952a-11eb-94f0-e9d6fcd3dcb4.png)
after:
![Screenshot from 2021-04-04 09-45-15](https://user-images.githubusercontent.com/1468842/113502166-ca4ad900-952a-11eb-881d-b3d324405fc4.png)

That did produce any significant improvement or change in CPU load.  - do those items count as SVGs? or are they part of one bigger svg that is transformed as one?

It seems that the pyvips version still suffers for a slightly uneven update rate on the glasses at 0.2s interval (similar to what it did on a desktop browser on 0.1s update_interval.)

Overall, pyvips less data, and seems to be less affected by poor wifi lin, also uses less CPU, and may therefore be the better option.
What are your thoughts on things I should try to make it smoother? 

Interesting Remi-findings:
if some Wifi noise/collisions are introduced, the blue animated square is quick to spawn.  - however, if the wifi link is dropped completely, then the last frame will be displayed for about a minute, before the blue animation, resuming just fine on regained connection.

**Comment by AndKe** [comment]
The "uneven update rate" of the pyvips version seems to be related to the INOP, maybe less effective use of cache when changing color completely? - or bigger updates..  anyway - disabling INOP produces a nice 5Hz update with little jitter.

After running it for a while, CPU usage drops:  update_rate = 0.3,  CPU drops to 20% , and update_rate = 0.2, CPU drops to 25%
in comparison: the blue flipping square produces a steady at 60% CPU load.
I think some of the jitter in frame updates is caused by the png compression/decompression.
In an attempt to try if GIF decoding was faster, I tried to change "png" to "gif", but apparently that was not supported/did not work that easily. :)

**Comment by AndKe** [comment]
@dddomodossola   I understand if the last comments I wrote were too much to read, and inconclusive, not answering the main question: "And so you want to keep the performace version, and we have just to fix font and labels positions?"

And finally I can answer it clearly:

Yes, please make it look nice in pyvips  - the pyvips approach is great!
I did a few pyvips changes, as I wrote before, I suspected that gif format could prove more efficient, due to it's minimal color space.

I changed:
buf = x.write_to_buffer(".gif", format="GIF")

and a few references to "png", the results are great!
in chromium browser on desktop even update_rate of 0.1 seconds work fine.
Glass:  update_rate=0.2   17..21% CPU usage
Glass:  update_rate=0.1   26..35% CPU usage
the updates are in a timely fashion, and the TCP traffic seems to be about 33% of that of PNG.

pyvips gif generation is a bit much for the Rpi4 (the whole thing runs slower than with png) - I find that odd and will investigate a bit. - if not, it is trivial to throw more processing power on that.

For now, we can use png, I can switch to gif later.  - there is also some hope for PNG8

**Comment by dddomodossola** [comment]
@AndKe Don't worry for writing to much and please excuse me for late replies. I however read it and I will work on this soon.

**Comment by dddomodossola** [comment]
I've done some graphical adjustments. Please give it a try.

**Comment by AndKe** [comment]
I will do, tomorrow. 
What is pyvvips / vips is recompressing to png/gif? - is it fed a bitmap or a svg ? - is the svg the full/whole thing I see in the brower?
 - or are there other elements as well?
 I am thinking of how I can make a synthetic speed test of compressing the data - maybe I can find a faster way (I find it strange that compression to PNG is that much more efficient than GIF)

**Comment by AndKe** [comment]
Thank you.
This is the visa vs "normal" version:
![Screenshot from 2021-04-10 14-52-03](https://user-images.githubusercontent.com/1468842/114270420-7ea59d00-9a0c-11eb-954e-04fb4934a489.png)

There is something to be desired with the readability of the font. maybe if it's larger, it would be better - the font itself uses the filled "zero" sign, which does not help.
The whole graphical item is smaller than before.

**Comment by dddomodossola** [comment]
@AndKe I will try to adjust the readability ;-)

**Comment by dddomodossola** [comment]
@AndKe changed the font

**Comment by AndKe** [comment]
Thank you, this is much better.
