### ISSUE TITLE
Odd webpage size issue.

### ISSUE THREAD

**Issue by AndKe** [dddomodossola/PFD#8]
@dddomodossola  After the text areas got added, and resolution got changed to the native resolution for the glass, something odd happened:
(All screenshots are in the order of: Firefox, google glass, chromium)

This is how the web page loads, like it is zoomed in.:
![Screenshot from 2021-03-12 23-25-02](https://user-images.githubusercontent.com/1468842/111005589-6568ec80-838b-11eb-905c-3d43a339eebc.png)

I can scroll down:
![Screenshot from 2021-03-12 23-25-15](https://user-images.githubusercontent.com/1468842/111005729-9cd79900-838b-11eb-83f1-5365206d9cd7.png)

I can also zoom out...
![Screenshot from 2021-03-12 23-26-17](https://user-images.githubusercontent.com/1468842/111005752-acef7880-838b-11eb-86fd-df40e467eead.png)

...But the text will remain below, with no backround
![Screenshot from 2021-03-12 23-26-22](https://user-images.githubusercontent.com/1468842/111005768-b4af1d00-838b-11eb-8286-9675cbc2e52d.png)

I am not sure why this is happening, why the text is treated so differently. - can it be some kind of responsive attempt ?
The synchronisation issue may be due to the glass working hard and slow on this page, maybe due to the re-ordering/scaling of it all the time..

**Comment by AndKe** [comment]
Maybe this old information will help: https://firt.dev/google-glass-browser/#responsive-web-design

**Comment by dddomodossola** [comment]
Hello André, the problem seems to be that gridbox layout is not supported by google glasses. I have to use a different layout.

**Comment by dddomodossola** [comment]
Hello @AndKe I pushed some updates, you get now another type of container that should be compatible with glasses.
Furthermore I added the thread to simulate data ;-)

**Comment by AndKe** [comment]
Wow. is there anything you can't do?
- now, can you please make google glass perform as if it had a Intel i9-10900 CPU?  :)

Ok - the webpage looks wonderful - you nailed it.

Some observations on performance vs different update_interval setting:
0.4  : gives barely noticeable latency between workstation and glass (staring at altitude numbers thru glass on the monitor, looking at them both side by side)
0.3 : still good, slightly more latency.
0.2 : some updates are skipped, much more latency  (when stopping the python, even the animated box comes later)
0.1 : serious trouble, updates now and then, often >4 seconds after.

High update rates on desktop is absolutely supernice and smooth.

Obviously, this is somehow a bit much for the glass.  but 0.4 is highly functional - less smooth and nice but does the job.
Which elements do you think are the most CPU intensive (on the glass side)?

If a widget is updated at 10hz using  ``` self.pfd.set_attitude_pitch(float(pitch)) ```  - is this in any way affecting the glass?  - or is glass only seeing an update at a rate defined in update_interval  ?

Also: is a pitch changing from 10.24339 to 10.24768 in any way more CPU intensive for the browser/glass than if the value was rounded to one decimal (so that both updates were 10.2)  - or an integer?

I am asking, because I do not know the way the changes are transferred to the browser, and whatever the browser does many calculations, or update only changed items - or redraw it all every time.

**Comment by dddomodossola** [comment]
1. If a widget is updated at 10hz using self.pfd.set_attitude_pitch(float(pitch)) - is this in any way affecting the glass? - or is glass only seeing an update at a rate defined in update_interval ? **glasses are affected only by update_interval**
2. Also: is a pitch changing from 10.24339 to 10.24768 in any way more CPU intensive for the browser/glass than if the value was rounded to one decimal (so that both updates were 10.2) - or an integer? **Decimals causes that also little changes generates an update. So reducing decimals will make little changes to be ignored and less CPU usage.**
3. I am asking, because I do not know the way the changes are transferred to the browser, and whatever the browser does many calculations, or update only changed items - or redraw it all every time. 
**Remi update logic is a bit complex to explain.** Here are some details:
- Updates are spawn to clients at *update_interval* rate;
- If a widget changes multiple times between two update intervals, only the latest update will be sent to the clients (however the server will process all the updates.)
- The widgets are organized in a tree. If a leaf changes, only the leaf will be updated. If two leafs belonging to the same branch change, the entire branch is updated. When a branch is updated, leafs that has not changed are not processed, the latest image is used.

I hope this clarifies some doubts. ;-)

**Comment by AndKe** [comment]
Thank you. 
This answered all my questions perfectly, my main concern was that I should not cause more updates when processing real data that changes frequently.  I will do rounding as there is no gain in displaying high-precision elements at such slow rate.
Maybe I once run it on something more powerful at higher refresh-rates.
